-- ============================================================================
-- EFETIVA OS — Test Suite 09A: Quotation Archiving + Supplier Auto Code
-- 20 assertions covering archive/unarchive lifecycle and supplier code gen
-- ============================================================================

begin;

select plan(20);

-- ---------------------------------------------------------------------------
-- Helper: create test data
-- ---------------------------------------------------------------------------

-- A1. Archive a draft quotation
-- A2. Archived quotation has archived_at set
-- A3. Archived quotation preserves original status
-- A4. Archived quotation preserves items
-- A5. Unarchive restores archived_at to null
-- A6. Unarchived quotation preserves status
-- A7. Double archive denied
-- A8. Double unarchive denied
-- A9. Archive non-existent denied
-- A10. Unarchive non-existent denied
-- A11. Archived hidden from default list (archived_at IS NULL filter)
-- A12. Archived filter shows archived
-- A13. Archive an active quotation
-- A14. Archive preserves supplier_id
-- A15. Archive preserves reference_number

-- B1. Supplier code format matches FOR-XXXXXX
-- B2. Supplier code is unique
-- B3. Supplier code is NOT NULL
-- B4. New supplier gets code automatically
-- B5. Supplier code immutability (UPDATE denied)
-- B6. Supplier code not reused after deletion

-- ===========================================================================
-- PART A: Quotation Archiving
-- ===========================================================================

-- Setup: create a test supplier
insert into public.suppliers (name, active) values ('Arquivo Teste Supplier', true);
-- note: code is auto-generated by default

-- Setup: create a test quotation (draft)
insert into public.quotations (supplier_id, reference_number, received_at, valid_until, status)
select s.id, 'REF-ARCH-001', current_date, current_date + interval '30 day', 'draft'
from public.suppliers s
where s.name = 'Arquivo Teste Supplier'
limit 1;

-- Setup: add an item to the quotation
insert into public.quotation_items (quotation_id, catalog_item_id, supplier_description, unit_price)
select q.id, ci.id, 'Item de teste', 25.50
from public.quotations q
join public.suppliers s on s.id = q.supplier_id
join public.catalog_items ci on ci.active = true
where s.name = 'Arquivo Teste Supplier'
  and q.reference_number = 'REF-ARCH-001'
limit 1;

-- A1. Archive a draft quotation
select lives_ok(
  $$select public.archive_quotation((
    select q.id from public.quotations q
    join public.suppliers s on s.id = q.supplier_id
    where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-001'
    limit 1
  ))$$,
  'archive_quotation succeeds for draft'
);

-- A2. Archived quotation has archived_at set
select ok(
  (select archived_at is not null from public.quotations q
   join public.suppliers s on s.id = q.supplier_id
   where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-001' limit 1),
  'archived_at is set after archive'
);

-- A3. Archived quotation preserves original status
select is(
  (select status::text from public.quotations q
   join public.suppliers s on s.id = q.supplier_id
   where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-001' limit 1),
  'draft',
  'original status preserved after archive'
);

-- A4. Archived quotation preserves items
select is(
  (select count(*)::int from public.quotation_items qi
   join public.quotations q on q.id = qi.quotation_id
   join public.suppliers s on s.id = q.supplier_id
   where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-001'),
  1,
  'items preserved after archive'
);

-- A5. Unarchive restores archived_at to null
select lives_ok(
  $$select public.unarchive_quotation((
    select q.id from public.quotations q
    join public.suppliers s on s.id = q.supplier_id
    where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-001'
    limit 1
  ))$$,
  'unarchive_quotation succeeds'
);

-- A6. Unarchived quotation preserves status
select is(
  (select status::text from public.quotations q
   join public.suppliers s on s.id = q.supplier_id
   where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-001' limit 1),
  'draft',
  'status preserved after unarchive'
);

-- A7. Double archive denied
select throws_ok(
  $$select public.archive_quotation((
    select q.id from public.quotations q
    join public.suppliers s on s.id = q.supplier_id
    where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-001'
    limit 1
  ))$$,
  'ja esta arquivada',
  'double archive is denied'
);

-- A8. Double unarchive denied (archive first, then try double unarchive)
select public.archive_quotation((
  select q.id from public.quotations q
  join public.suppliers s on s.id = q.supplier_id
  where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-001'
  limit 1
));

select public.unarchive_quotation((
  select q.id from public.quotations q
  join public.suppliers s on s.id = q.supplier_id
  where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-001'
  limit 1
));

select throws_ok(
  $$select public.unarchive_quotation((
    select q.id from public.quotations q
    join public.suppliers s on s.id = q.supplier_id
    where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-001'
    limit 1
  ))$$,
  'nao esta arquivada',
  'double unarchive is denied'
);

-- A9. Archive non-existent denied
select throws_ok(
  $$select public.archive_quotation('00000000-0000-0000-0000-000000000000'::uuid)$$,
  'nao encontrada',
  'archive non-existent is denied'
);

-- A10. Unarchive non-existent denied
select throws_ok(
  $$select public.unarchive_quotation('00000000-0000-0000-0000-000000000000'::uuid)$$,
  'nao encontrada',
  'unarchive non-existent is denied'
);

-- A11. Archived hidden from default list (archived_at IS NULL filter)
-- After archive, the quotation should NOT appear when filtering archived_at IS NULL
select public.archive_quotation((
  select q.id from public.quotations q
  join public.suppliers s on s.id = q.supplier_id
  where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-001'
  limit 1
));

select is(
  (select count(*)::int from public.quotations q
   join public.suppliers s on s.id = q.supplier_id
   where s.name = 'Arquivo Teste Supplier'
     and q.reference_number = 'REF-ARCH-001'
     and q.archived_at is null),
  0,
  'archived quotation hidden from default list'
);

-- A12. Archived filter shows archived
select is(
  (select count(*)::int from public.quotations q
   join public.suppliers s on s.id = q.supplier_id
   where s.name = 'Arquivo Teste Supplier'
     and q.reference_number = 'REF-ARCH-001'
     and q.archived_at is not null),
  1,
  'archived quotation appears in archived filter'
);

-- A13. Archive an active quotation
-- Create an active quotation
insert into public.quotations (supplier_id, reference_number, received_at, valid_until, status)
select s.id, 'REF-ARCH-ACT', current_date, current_date + interval '30 day', 'active'
from public.suppliers s
where s.name = 'Arquivo Teste Supplier' limit 1;

select ok(
  (select archived_at is not null from public.quotations q
   join public.suppliers s on s.id = q.supplier_id
   where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-ACT'
   limit 1),
  'active quotation can be archived'
);

-- A14. Archive preserves supplier_id
select is(
  (select q.supplier_id = s.id from public.quotations q
   join public.suppliers s on s.id = q.supplier_id
   where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-ACT'
   limit 1),
  true,
  'supplier_id preserved after archive'
);

-- A15. Archive preserves reference_number
select is(
  (select q.reference_number from public.quotations q
   join public.suppliers s on s.id = q.supplier_id
   where s.name = 'Arquivo Teste Supplier' and q.reference_number = 'REF-ARCH-ACT'
   limit 1),
  'REF-ARCH-ACT',
  'reference_number preserved after archive'
);

-- ===========================================================================
-- PART B: Supplier Auto Code
-- ===========================================================================

-- B1. Supplier code format matches FOR-XXXXXX
select matches(
  (select code from public.suppliers where name = 'Arquivo Teste Supplier' limit 1),
  '^FOR-[0-9]{6}$',
  'supplier code matches FOR-XXXXXX format'
);

-- B2. Supplier code is unique
select is(
  (select count(distINCT code) from public.suppliers),
  (select count(*) from public.suppliers),
  'all supplier codes are unique'
);

-- B3. Supplier code is NOT NULL
select ok(
  (select not exists(select 1 from public.suppliers where code is null)),
  'no supplier has null code'
);

-- B4. New supplier gets code automatically
insert into public.suppliers (name, active) values ('Auto Code Teste', true);
select matches(
  (select code from public.suppliers where name = 'Auto Code Teste' limit 1),
  '^FOR-[0-9]{6}$',
  'new supplier gets auto-generated code'
);

-- B5. Supplier code immutability (UPDATE denied)
select throws_ok(
  $$update public.suppliers set code = 'FOR-999999' where name = 'Auto Code Teste'$$,
  'codigo do fornecedor nao pode ser alterado',
  'code update is denied'
);

-- B6. Supplier code not reused after deletion (inactivation instead)
-- Inactivate supplier, verify code is not reused by next insert
update public.suppliers set active = false where name = 'Auto Code Teste';

insert into public.suppliers (name, active) values ('Reusage Teste', true);

select isnt(
  (select code from public.suppliers where name = 'Reusage Teste' limit 1),
  (select code from public.suppliers where name = 'Auto Code Teste' limit 1),
  'new supplier code is different from inactivated supplier code'
);

select * from finish();
rollback;
